### ISSUE TITLE
Current Build (as of 8 April 2024) doesn't work

### ISSUE THREAD

**Issue by Kalanyr** [ActiveIce/Magisk_zygote64_32#1]
The Magisk App is incapable of patching init_boot, I also tested with the March init_boost which I tested with a previous build.

**Comment by ActiveIce** [comment]
try the latest build

**Comment by Kalanyr** [comment]
Yup, fixed now,  updated to latest version of (your) Magisk and patched the
April init_boot and it worked.

Thanks.
